EnjoyDigitalUniversity/Models/Address.cs
namespace EnjoyDigitalUniversity.Models
{
    public class Address
    {
        public string AddressLine1 { get; set; }

        public string AddressLine2 { get; set; }

        public string AddressLine3 { get; set; }

        public string Town { get; set; }

        public string County { get; set; }

        public string Country { get; set; }
    }
}

EnjoyDigitalUniversity/Models/Course.cs
using System.Web;

namespace EnjoyDigitalUniversity.Models
{
    public class Course
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public IHtmlString BodyText { get; set; }

        public string Department { get; set; }

        public string Url { get; set; }
    }
}

EnjoyDigitalUniversity/Models/CourseListingViewModel.cs
using System.Collections.Generic;

namespace EnjoyDigitalUniversity.Models
{
    public class CourseListingViewModel
    {
        public IEnumerable<Course> Type { get; set; }

        public IEnumerable<Course> Courses { get; set; }

        public string Department { get; set; }
    }    
}

EnjoyDigitalUniversity/Models/Qualification.cs
namespace EnjoyDigitalUniversity.Models
{
    public class Qualification
    {
        public string Type { get; set; }

        public string Subject { get; set; }

        public string Grade { get; set; }
    }
}

EnjoyDigitalUniversity/Models/Student.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EnjoyDigitalUniversity.Models
{
    public class Student
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string EmailAddress { get; set; }

        public int CourseId { get; set; }

        public Address Address { get; set; }

        public IEnumerable<Qualification> Qualifications { get; set; }
    }
}

EnjoyDigitalUniversity/ViewModels/ApplicationViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using EnjoyDigitalUniversity.Models;
using Microsoft.Owin.BuilderProperties;

namespace EnjoyDigitalUniversity.ViewModels
{
    public class ApplicationViewModel
    {
    }    
}

EnjoyDigitalUniversity/ViewModels/CourseListingViewModel.cs
using System.Collections.Generic;
using System.Globalization;
using EnjoyDigitalUniversity.Models;
using Umbraco.Core.Models;
using Umbraco.Web.Models;

namespace EnjoyDigitalUniversity.ViewModels
{
    public class CourseListingViewModel : RenderModel
    {
        public CourseListingViewModel(IPublishedContent content, CultureInfo culture) : base(content, culture)
        {
        }

        public CourseListingViewModel(IPublishedContent content) : base(content)
        {
        }

        public IEnumerable<CourseViewModel> Courses { get; set; }

        public string Department { get; set; }

        public IEnumerable<string> Departments { get; set; }
    }    
}

EnjoyDigitalUniversity/ViewModels/CourseViewModel.cs
using System.Web;

namespace EnjoyDigitalUniversity.ViewModels
{
    public class CourseViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public IHtmlString BodyText { get; set; }

        public string Department { get; set; }

        public string Url { get; set; }
    }
}

EnjoyDigitalUniversity/ViewModels/CoursesViewModel.cs
using System.Collections.Generic;
using EnjoyDigitalUniversity.Models;

namespace EnjoyDigitalUniversity.ViewModels
{
    public class CoursesViewModel
    {
        public IEnumerable<CourseViewModel> Courses { get; set; }

        public string Department { get; set; }
    }    
}

EnjoyDigitalUniversity/Controllers/CourseController.cs
using System.Web.Mvc;
using EnjoyDigitalUniversity.Models;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using System.Web;
using EnjoyDigitalUniversity.Services;
using EnjoyDigitalUniversity.ViewModels;
using System.Linq;
using Newtonsoft.Json;
using System.Net;
using System.Net.Http;
using System.Text;
using System.IO;

namespace EnjoyDigitalUniversity.Controllers
{
    public class CourseController : SurfaceController
    {
        public CourseController()
        {
        }

        public PartialViewResult Listing(string department)
        {
            var model = new CoursesViewModel();

            TryUpdateModel(model);

            var courses = CurrentPage.Children.Where(child => child.DocumentTypeAlias == "course");

            if (!string.IsNullOrEmpty(department))
            {
                model.Department = department;

                courses = courses.Where(child => child.GetPropertyValue<string>("department") == department);
            }

            model.Courses =
                courses
                    .OrderBy(child => child.GetPropertyValue<string>("title"))
                    .Select(course =>
                        new CourseViewModel
                        {
                            Title = course.GetPropertyValue<string>("title", false),
                            BodyText = course.GetPropertyValue<IHtmlString>("bodyText", false),
                            Department = course.GetPropertyValue<string>("department", false),
                            Url = course.Url
                        }
                );

            return PartialView(model);
        }

        public PartialViewResult Detail()
        {
            var model = Map(CurrentPage);

            return PartialView(model);
        }

        public PartialViewResult ApplyForm()
        {
            var student = new Student
            {
                CourseId = CurrentPage.Id
            };

            return PartialView(student);
        }

        [HttpPost]
        public ActionResult Apply(Student student)
        {
            if (ModelState.IsValid)
            {
                var studentService = new StudentService();

                if(studentService.Exists(student))
                {
                    studentService.Save(student);

                    TempData["successmessage"] = "Student updated";
                }
                else
                {
                    studentService.Save(student);

                    TempData["successmessage"] = "Student added";
                }
            }

            return CurrentUmbracoPage();
        }

        public CourseViewModel Map(IPublishedContent content)
        {
            var course = new CourseViewModel();

            course.Id = content.Id;
            course.Title = content.GetPropertyValue<string>("title");
            course.Department = content.GetPropertyValue<string>("department");
            course.BodyText = content.GetPropertyValue<IHtmlString>("bodyText");
            return course;
        }
    }
}

EnjoyDigitalUniversity/Controllers/CourseListingController.cs
using EnjoyDigitalUniversity.ViewModels;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Core;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace EnjoyDigitalUniversity.Controllers
{
    public class CourseListingController : RenderMvcController
    {
        #region Actions

        public override ActionResult Index(RenderModel model)
        {
            var courseListing = new CourseListingViewModel(CurrentPage);
            var departments = GetAllDepartmentIds();

            TryUpdateModel(courseListing);

            courseListing.Departments = departments;

            return CurrentTemplate(courseListing);
        }

        #endregion

        #region Helpers

        private System.Collections.Generic.IEnumerable<string> GetAllDepartmentIds()
        {
            var allTypes = Umbraco.DataTypeService.GetAllDataTypeDefinitions();
            var typeId = allTypes.First(x => "Department".InvariantEquals(x.Name)).Id;
            var departments = Umbraco.DataTypeService.GetPreValuesByDataTypeId(typeId);
            return departments;
        }

        #endregion
    }
}

EnjoyDigitalUniversity/Views/BlogOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<div role="content">

	<section class="light blogarchive equalizer">
		<div class="container">

			<div class="row">
				@foreach(var post in CurrentPage.Children) 
				{
					<div class="col-sm-6">
						<div class="content equal">
							<a href="@post.Url">
								<div class="date">@post.CreateDate.ToLongDateString()</div>
								<h2>@post.Name</h2>		
								<p>@Umbraco.Truncate(post.Introduction, 240, true)</p>
							</a>
						</div>
					</div>
				}
			</div>
		</div>
	</section>

</div>

EnjoyDigitalUniversity/Views/BlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("content", "fanoe")

EnjoyDigitalUniversity/Views/Course.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<div class="umb-grid">
    <div class="grid-section">
        <div class="light">
            <div class="container">
                @Html.Action("Detail", "Course")
                @Html.Action("ApplyForm", "Course")                
            </div>
        </div>
    </div>
</div>

EnjoyDigitalUniversity/Views/Course/ApplyForm.cshtml
@inherits UmbracoViewPage<EnjoyDigitalUniversity.Models.Student>

@if(TempData["successmessage"] != null)
{
    <div>@TempData["successmessage"]</div>
}

@using (Html.BeginUmbracoForm("Apply", "Course", FormMethod.Post))
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>Student</h4>
    <hr/>
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CourseId)

    <div class="form-group">
      @Html.LabelFor(model => model.FirstName, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.LastName, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.EmailAddress, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => model.EmailAddress, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => model.EmailAddress, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => Model.Address.AddressLine1, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => Model.Address.AddressLine1, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => Model.Address.AddressLine1, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => Model.Address.AddressLine2, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => Model.Address.AddressLine2, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => Model.Address.AddressLine2, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => Model.Address.AddressLine3, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => Model.Address.AddressLine3, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => Model.Address.AddressLine3, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => Model.Address.Town, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => Model.Address.Town, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => Model.Address.Town, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => Model.Address.County, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => Model.Address.County, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => Model.Address.County, "", new {@class = "text-danger"})
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => Model.Address.Country, new {@class = "control-label col-md-2"})
      <div class="col-md-10">
        @Html.EditorFor(model => Model.Address.Country, new {htmlAttributes = new {@class = "form-control"}})
        @Html.ValidationMessageFor(model => Model.Address.Country, "", new {@class = "text-danger"})
      </div>
    </div>    

    <h4>Qualifications</h4>
    <hr/>

    <div id="Qualifications">
      <input id="Qualifications_Index" name="Qualifications.Index" type="hidden" value="1"/>

      <div class="form-group">
        <label class="control-label col-md-2">Type</label>
        <div class="col-md-10">
          <input id="Qualifications_1__Type" name="Qualifications[1].Type" type="text" value="" class="form-control"/>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-2">Subject</label>
        <div class="col-md-10">
          <input id="Qualifications_1__Subject" name="Qualifications[1].Subject" type="text" value="" class="form-control"/>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-2">Grade</label>
        <div class="col-md-10">
          <input id="Qualifications_1__Grade" name="Qualifications[1].Grade" type="text" value="" class="form-control"/>
        </div>
      </div>
    </div>

    <div>
      <br/>
      <a href="#" onclick="AddQualification();">Add Qualification</a>
    </div>   
    
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Apply" class="btn btn-default"/>
      </div>
    </div>
  </div>
}

<script>
  function AddQualification() {
    var tempIndex = Math.random().toString(36).substr(2, 5);
    var template = $('#RowTemplate');
    var insertItem = template.clone(false);
    insertItem.find('input').each(function() {
      this.id = this.id.replace('REPLACE_ID', tempIndex);
      this.name = this.name.replace('REPLACE_ID', tempIndex);
      this.value = this.value.replace('REPLACE_ID', tempIndex);
    });
    insertItem.show();
    $('#Qualifications').append(insertItem.contents());
  };
</script>
    
<div id="RowTemplate" style="display: none">

  <input id="Qualifications_Index" name="Qualifications.Index" type="hidden" value="REPLACE_ID"/>
  <div class="form-group">
    <label class="control-label col-md-2">Type</label>
    <div class="col-md-10">
      <input id="Qualifications_REPLACE_ID__Type" name="Qualifications[REPLACE_ID].Type" type="text" value="" />
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-2">Subject</label>
    <div class="col-md-10">
      <input id="Qualifications_REPLACE_ID__Subject" name="Qualifications[REPLACE_ID].Subject" type="text" value="" />
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-2">Grade</label>
    <div class="col-md-10">
      <input id="Qualifications_REPLACE_ID__Grade" name="Qualifications[REPLACE_ID].Grade" type="text" value="" />
    </div>
  </div>     
</div>

EnjoyDigitalUniversity/Views/Course/Detail.cshtml
@model EnjoyDigitalUniversity.ViewModels.CourseViewModel
<div class="row clearfix">
  <div class="col-md-12 column">
    <div>
      <h1>@Model.Title</h1>
      <h2>@Model.Department</h2>
      <p>@Model.BodyText</p>
    </div>   
  </div>
</div>

EnjoyDigitalUniversity/Views/Course/Listing.cshtml
@model EnjoyDigitalUniversity.ViewModels.CoursesViewModel

@if (Model.Courses != null && Model.Courses.Any())
{
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div>
                <h1>@(string.IsNullOrEmpty(Model.Department) ? "All courses" : Model.Department)</h1>

                @if (Model.Courses != null && Model.Courses.Any())
                {
                    foreach (var course in Model.Courses)
                    {
                        @Html.Partial("Course/Listing", course)
                    }
                }
            </div>
        </div>
    </div>
}

EnjoyDigitalUniversity/Views/CourseListing.cshtml
@inherits UmbracoViewPage<EnjoyDigitalUniversity.ViewModels.CourseListingViewModel>
@{
    Layout = "Master.cshtml";
}

<div class="umb-grid">
    <div class="grid-section">
        <div class="light">
            <div class="container">
                @using (Html.BeginUmbracoForm("Listing", "Course", null, new { @class = "js-ajax-form", data_holder = "form-output" }, FormMethod.Post))
                {
                    <div>
                        @Html.DropDownList(
                            "department",
                            new SelectList(
                                Model.Departments.Select(x => new { Value = x, Text = x }),
                                "Value",
                                "Text"
                            ),
                            "--- Select Department ---"
                        )
                    </div>
                    <input type="submit" value="Search" />
                }
                <div class="form-output">
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="/scripts/forms.js"></script>
}

EnjoyDigitalUniversity/Views/Department.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Department>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

EnjoyDigitalUniversity/Views/DepartmentListing.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.DepartmentListing>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

EnjoyDigitalUniversity/Views/Home.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("content", "fanoe")

EnjoyDigitalUniversity/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EnjoyDigitalUniversity/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EnjoyDigitalUniversity/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

EnjoyDigitalUniversity/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
    var home = @CurrentPage.Site();
}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="@CurrentPage.siteDescription">

    <title>@CurrentPage.Name | @CurrentPage._siteTitle</title>

    <!-- Fonts -->
    <link href="//fonts.googleapis.com/css?family=Merriweather:400,700,300,900" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet" type="text/css">

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/fanoe.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-xs-8 col-sm-12 col-md-4">
                    <a href="@home.Url">
                        <div class="brand" style="background-image:url('@(home.SiteLogo)?height=65&width=205&bgcolor=000')"></div>
                    </a>
                </div>
                <div class="col-sm-12 col-md-8">
                    <nav>

                        @{ Html.RenderPartial("MainNavigation"); }

                    </nav>
                </div>
            </div>
        </div>

        <div id="toggle" class="toggle">
            <a href="#" class="cross"><span></span></a>
        </div>
    </header>

    @RenderBody()

    <footer class="field dark">
        <div class="container">
            <div class="row">

                @{ Html.RenderPartial("BottomNavigation"); }

            </div>
        </div>
    </footer>

    <!-- Javascripts -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/scripts/fanoe.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

EnjoyDigitalUniversity/Views/Partials/BottomNavigation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{ 
    var home = CurrentPage.Site();
}

@if (home.Children.Where("Visible").Any())
{
    @* For each child page under the home node, where the property umbracoNaviHide is not True *@
    foreach (var childPage in home.Children.Where("Visible"))
    {   
        <div class="col-xs-6 col-sm-3">
            @if (childPage.Children.Where("Visible").Any())
            {                    
                <strong>@childPage.Name</strong>
                if(childPage.DocumentTypeAlias != "courseListing")
                {
                    @childPages(childPage.Children)
                }
            }
        </div>
    }
}

<div class="col-xs-6 col-sm-3">
    <strong>Find us</strong>
    <ul>
        <li>
            <a href="https://twitter.com/umbracoproject" target="_blank">Twitter</a>
        </li>
        <li>
            <a href="https://www.facebook.com/Umbraco" target="_blank">Facebook</a>
        </li>
        <li>
            <a href="http://umbraco.com/?utm_source=core&utm_medium=starterkit&utm_content=topic-link&utm_campaign=fanoe" target="_blank">Umbraco.com</a>
        </li>
    </ul>
</div>

@helper childPages(dynamic pages)
{
    @* Ensure that we have a collection of pages *@
    if (pages.Any())
    {
        <ul>
            @foreach (var page in pages.Where("Visible"))
            {
                <li>
                    <a href="@page.Url">@page.Name</a>
                </li>
            }
        </ul>
    }
}

EnjoyDigitalUniversity/Views/Partials/Course/Listing.cshtml
@model EnjoyDigitalUniversity.ViewModels.CourseViewModel

<div>
    <h2>@Model.Title</h2>
    <div>@Model.BodyText</div>
    <div>Department: @Model.Department</div>
    <div><a href="@Model.Url">View course</a></div>
    <br />
</div>

EnjoyDigitalUniversity/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

EnjoyDigitalUniversity/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

EnjoyDigitalUniversity/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

EnjoyDigitalUniversity/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

EnjoyDigitalUniversity/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("content", "fanoe")